" My vim config
set tabstop=4
set shiftwidth=4
set autoindent
set number
"set expandtab
set softtabstop=4

" 禁用鼠标
set mouse=

"source ~/.vim/test.vim


map! <C-A> <ESC>I

map! <C-E> <ESC>A

"echo "这是一个vim echo 语句"

"set foldmethod=indent
"manual           手工定义折叠
"indent             更多的缩进表示更高级别的折叠
"expr                用表达式来定义折叠
"syntax             用语法高亮来定义折叠
"diff                  对没有更改的文本进行折叠
"marker            对文中的标志折叠



"autocmd BufReadPost *.py,*.c,*.go :set tabstop=4 sw=4
autocmd BufReadPost,BufNewFile *.py,*.c,*.go,*.yml,*.yaml :set expandtab softtabstop=4

