[program:nginx]
command=nginx -g 'daemon off;'
#command=nginx
startsecs=0
startretries=1
autorestart=unexpected
exitcodes=0,1

#redirect_stderr=true
stdout_logfile=%(ENV_SUPERVISORD_ROOT)s/logs/%(program_name)s-access.log
stderr_logfile=%(ENV_SUPERVISORD_ROOT)s/logs/%(program_name)s-error.log

stdout_logfile_maxbytes=%(ENV_SUPERVISORD_LOG_SIZE)s
stdout_logfile_backups=%(ENV_SUPERVISORD_LOG_BACKUPS)s

stderr_logfile_maxbytes=%(ENV_SUPERVISORD_LOG_SIZE)s
stderr_logfile_backups=%(ENV_SUPERVISORD_LOG_BACKUPS)s
