[program:ttyd]
#command=ttyd -6 -i :: -p 57681 -W --cwd %(ENV_HOME)s bash --login
command=ttyd -6 -p 57681 -W -S -C %(ENV_HOME)s/.supervisord/fullchain.pem -K %(ENV_HOME)s/.supervisord/privkey.pem -c "username:password" --cwd %(ENV_HOME)s bash --login
autostart=true
redirect_stderr=true
stdout_logfile=%(ENV_SUPERVISORD_ROOT)s/logs/%(program_name)s.log
stdout_logfile_maxbytes=%(ENV_SUPERVISORD_LOG_SIZE)s
stdout_logfile_backups=%(ENV_SUPERVISORD_LOG_BACKUPS)s
